language: php

os:
  - linux

git:
  depth: 1

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1


matrix:
  fast_finish: true

sudo: false

dist: precise

install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --no-interaction
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
    - mkdir -p build/logs
    - ls -al

# Testing the app (see phpunit.xml), generating Code Coverage report
script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


#after_script:


after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v
# Submit coverage report to codecov.io
# - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# Configure email notifications
notifications:
     email:
        on_success: never
        on_failure: always

# You can delete cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer